---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(monocle)
library(CellChat)
library(SCENIC)
```

```{r}
proj <- "BRCA_RNAmeth_TME"
sc_proj <- "TNBC"
```

# 单细胞数据集
```{r}
load(paste0("Rdata/",proj,"_",sc_proj,"_SC.Rdata"))
celltype <- "NK cells"
scRNA_sub.nmf <- readRDS(paste0("Rdata/NMF_cluster/scRNA_nmf_",celltype,".Rds"))


dir.create(paste0("Rdata/",celltype))
dir.create(paste0("table/",celltype))
dir.create(paste0("plot/",celltype))
```

# 获取基因集
```{r}
rna_meth <- read.csv("geneset/RNA_modification_regulator.csv",header = T)
rnameth_g <- rna_meth$gene[rna_meth$regulator_type == "writter"]
# rnameth_g <- rna_meth$gene
```

# 拟时序
```{r}
# if(!file.exists(paste0("Rdata/",celltype,"/psedocds.Rdata"))){
# 
countMatrix <- GetAssayData(scRNA_sub.nmf, assay = 'RNA', slot = 'counts')

cellanno <- new('AnnotatedDataFrame', data = scRNA_sub.nmf@meta.data)

geneinfo <- data.frame(gene_short_name = rownames(countMatrix),row.names = rownames(countMatrix))
geneinfo <- new('AnnotatedDataFrame', data = geneinfo)

cds <- newCellDataSet(cellData = countMatrix,
                      phenoData = cellanno,
                      featureData = geneinfo,
                      expressionFamily = negbinomial.size())


cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds, cores=4, relative_expr = TRUE)

##使用monocle选择的高变基因，不修改
disp_table <- dispersionTable(cds)
disp.genes <- subset(disp_table, mean_expression >= 0.1 & dispersion_empirical >= 1 * dispersion_fit)$gene_id
cds <- setOrderingFilter(cds, disp.genes)
plot_ordering_genes(cds)

#降维
cds <- reduceDimension(cds, max_components = 2, method = 'DDRTree')
#排序，报错请用4.1以上的R，并重装monocle
cds <- orderCells(cds)
save(cds,file = paste0("Rdata/",celltype,"/psedocds.Rdata"))
# }
# load(paste0("Rdata/",celltype,"/psedocds.Rdata"))

cg <- intersect(rnameth_g,rownames(scRNA_sub.nmf))

my_pseudotime_cluster <- plot_pseudotime_heatmap(cds[cg,],
                                                 # num_clusters = 2, # add_annotation_col = ac,
                                                 show_rownames = TRUE,
                                                 return_heatmap = TRUE)

png(paste0("plot/",celltype,"/psedocluster_cg.png"),units="in", width=6, height=8,res=300)
print(my_pseudotime_cluster)
dev.off()


#State轨迹分布图
plot1 <- plot_cell_trajectory(cds, color_by = "State")
plot1

plot2 <- plot_cell_trajectory(cds, color_by = "NMF_gene_celltype")
plot2

##合并出图
png(paste0("plot/",celltype,"/psedo_nmfcluster_trajectory(NMF_gene).png"),units="in", width=8, height=10,res=300)
plot1/plot2
dev.off()
```

# 细胞通讯（上皮+免疫细胞）
```{r}
gc()
cell.use <- as.character(unique(scRNA_sub.nmf$NMF_gene_celltype))

table(scRNA_tnbc$celltype_select)
scRNA_select <- subset(scRNA_tnbc, celltype_select %in% c("Cancer Epithelial","CAFs","Macrophage","DCs","B-cells","T cells CD4+","T cells CD8+"))

scRNA_select$NMF_gene_celltype <- scRNA_select$celltype_select
scRNA_select$NMF_gene_celltype <- scRNA_select$celltype_select
scRNA_chat = merge(scRNA_select,scRNA_sub.nmf)
table(scRNA_chat$NMF_gene_celltype)
table(scRNA_chat$NMF_gene_celltype)
scRNA_chat <- NormalizeData(scRNA_chat)

dataMatrix <- GetAssayData(scRNA_chat, slot = "data")
cellanno <- scRNA_chat@meta.data
cellchat <- createCellChat(object = dataMatrix, meta = cellanno,group.by = "NMF_gene_celltype")#针对不同细胞类型进行的细胞互作
cellchat <- setIdent(cellchat,ident.use = "NMF_gene_celltype")

CellChatDB <- CellChatDB.human 
groupSize <- as.numeric(table(cellchat@idents))
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling") 
cellchat@DB <- CellChatDB.use 

# dplyr::glimpse(CellChatDB$interaction)
cellchat <- subsetData(cellchat)# 提取数据库支持的数据子集
cellchat <- identifyOverExpressedGenes(cellchat)# 识别过表达基因
cellchat <- identifyOverExpressedInteractions(cellchat)# 识别配体-受体对
cellchat <- projectData(cellchat, PPI.human)# 将配体、受体投射到PPI网络
unique(cellchat@idents)
cellchat <- computeCommunProb(cellchat)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)

df.net<- subsetCommunication(cellchat)
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))

png(paste0("plot/",celltype,"/Interactions_num(Cancer_source)(NMF_gene).png"),units="in", width=5, height=5,res=300)
netVisual_circle(cellchat@net$count, vertex.weight = groupSize, 
                 weight.scale = T, label.edge= T, 
                 sources.use = 'Cancer Epithelial',targets.use = cell.use,
                 title.name = "Number of interactions")
dev.off()

png(paste0("plot/",celltype,"/Interactions_weights(Cancer_source)(NMF_gene).png"),units="in", width=5, height=5,res=300)
netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, 
                 weight.scale = T, label.edge= T, 
                 sources.use = 'Cancer Epithelial',targets.use = cell.use,
                 title.name = "Interaction weights/strength")
dev.off()


lapply(cell.use, function(cell){
png(paste0("plot/",celltype,"/Interactions_num(",cell,"_source)(NMF_gene).png"),units="in", width=5, height=5,res=300)
netVisual_circle(cellchat@net$count, vertex.weight = groupSize, 
                 weight.scale = T, label.edge= T, 
                 sources.use = cell,
                 title.name = "Number of interactions")
dev.off()
})


cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")
h1=netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing")
h2=netAnalysis_signalingRole_heatmap(cellchat, pattern = "incoming")

png(paste0("plot/",celltype,"/signalingRole_heatmap(NMF_gene).png"),units="in", width=15, height=8,res=300)
h1 + h2
dev.off()


p1 <- netVisual_bubble(cellchat,
                 targets.use = cell.use,
                 sources.use = setdiff(unique(scRNA_chat$NMF_gene_celltype),cell.use),
                 remove.isolate = FALSE)+coord_flip()

p2 <- netVisual_bubble(cellchat,
                 targets.use = setdiff(unique(scRNA_chat$NMF_gene_celltype),cell.use),
                 sources.use = cell.use,
                 remove.isolate = FALSE)+coord_flip()
png(paste0("plot/",celltype,"/signal_bubble(NMF_gene).png"),units="in", width=10, height=12,res=300)
p1/p2

```

# SCENIC

```{r}
if(F){
gc()
dir.create(paste0("SCENIC/",celltype))
dir.create(paste0("SCENIC/",celltype,"/int"))
dir.create(paste0("SCENIC/",celltype,"/output"))
int_delete <- list.files("int/")
out_delete <- list.files("output/")

# 复制选中文件
sapply(int_delete,function(x){file.remove(paste0("int/",x))})
sapply(out_delete,function(x){file.remove(paste0("output/",x))})

set.seed(9985)
sample.use <- scRNA_sub.nmf@meta.data %>% rownames_to_column("cell_id") %>%  group_by(scRNA_sub.nmf$NMF_gene_celltype) %>% slice_sample(n = 300) %>% select(cell_id)

if(!file.exists(paste0("SCENIC/",celltype,"/scenicOptions_final.Rds"))){

exprMat <- as.matrix(scRNA_sub.nmf@assays$RNA@counts)
cellInfo <- scRNA_sub.nmf@meta.data
saveRDS(cellInfo, file=paste0("SCENIC/",celltype,"/int/cellInfo.Rds"))

mydbDIR <- "SCENIC/cisTarget_databases/"
mydbs <- c("mm9-5kb-mc8nr" = "hg19-tss-centered-10kb-7species.mc9nr.feather")

scenicOptions <- initializeScenic(org="hgnc", 
                                  nCores=4,
                                  dbDir=mydbDIR, 
                                  dbs = mydbs,
                                  datasetTitle = "os")
saveRDS(scenicOptions, paste0("SCENIC/",celltype,"/int/scenicOptions.rds"))

# 基因过滤（基因表达量之和>细胞数*3%，且在1%的细胞中表达）
genesKept <- geneFiltering(exprMat, scenicOptions, 
                           minCountsPerGene = 3 * 0.01 * ncol(exprMat), 
                           minSamples = ncol(exprMat) * 0.01)

exprMat_filtered <- exprMat[genesKept, ]

# 计算相关性矩阵
runCorrelation(exprMat_filtered, scenicOptions)

# 共表达分析
exprMat_filtered_log <- log2(exprMat_filtered+1) 
runGenie3(exprMat_filtered_log, scenicOptions, nParts = 10)


scenicOptions@settings$nCores <- 4
exprMat_log <- log2(exprMat+1)

gc()
# 基于共表达情况推断共表达模块
scenicOptions <- runSCENIC_1_coexNetwork2modules(scenicOptions)

# Motif验证共表达模块（利用cisTarget数据库，删除共表达模块内与motif评分不高的基因，得到调控单元regulons）
scenicOptions@settings$nCores <- 1
gc()
# scenicOptions <- runSCENIC_2_createRegulons(scenicOptions,
#                                             coexMethod=c("top5perTarget"))
scenicOptions <- runSCENIC_2_createRegulons(scenicOptions,
                                            coexMethod=c("top50"))
# Regulon活性评分与可视化（AUCell）
library(doParallel)
scenicOptions <- runSCENIC_3_scoreCells(scenicOptions, exprMat_log) 

# Regulon活性二进制转换与可视化
scenicOptions <- runSCENIC_4_aucell_binarize(scenicOptions)

saveRDS(scenicOptions, file=paste0("SCENIC/",celltype,"/scenicOptions_final.Rds"))  

int_tobeCopy <- list.files("int/")
out_tobeCopy <- list.files("output/")

# 复制选中文件
sapply(int_tobeCopy,function(x){file.copy(paste("int",x,sep="/"),paste0("SCENIC/",celltype,"/int/"))})
sapply(out_tobeCopy,function(x){file.copy(paste("output",x,sep="/"),paste0("SCENIC/",celltype,"/output/"))})

}

scenicOptions <- readRDS(paste0("SCENIC/",celltype,"/scenicOptions_final.Rds"))
int_tobeCopy <- list.files(paste0("SCENIC/",celltype,"/int/"))
out_tobeCopy <- list.files(paste0("SCENIC/",celltype,"/output/"))
sapply(int_tobeCopy,function(x){file.copy(paste0("SCENIC/",celltype,"/int/",x),paste0("int/"))})
sapply(out_tobeCopy,function(x){file.copy(paste0("SCENIC/",celltype,"/output/",x),"output/")})


aucell_regulonAUC <- loadInt(scenicOptions, "aucell_regulonAUC")
aucell_regulonAUC
aucell_regulonAUC.t <- t(aucell_regulonAUC@assays@data$AUC)
colnames(aucell_regulonAUC.t) <- gsub(" ", "_", colnames(aucell_regulonAUC.t))
rownames(aucell_regulonAUC.t) <- gsub("[.]", "-", rownames(aucell_regulonAUC.t))

scRNA.scenic <- scRNA_sub.nmf
# 结果导入
scRNA.scenic@meta.data <- cbind(scRNA.scenic@meta.data, aucell_regulonAUC.t[rownames(scRNA.scenic@meta.data),])

# DimPlot(scRNA.scenic, reduction = "umap")
# 找6个
# FeaturePlot(scRNA.scenic, reduction = "umap", features = colnames(scRNA.scenic@meta.data)[20:27], cols = c("yellow", "red"))

#Regulon scores heatmap 热图
Idents(scRNA.scenic)=scRNA.scenic$NMF_gene_celltype
cells.ord.cluster <- scRNA.scenic@active.ident
cells.ord.cluster<- cells.ord.cluster[order(cells.ord.cluster)]
regulon.scores <- t(aucell_regulonAUC.t[names(cells.ord.cluster),])
regulon.scores.log <- log(regulon.scores +1)
regulon.scores.scaled <- scale(regulon.scores)

library(gplots)
library(pheatmap)

# 进一步标化
cal_z_score <- function(x){
  (x - mean(x)) / sd(x)
}
data_subset_norm <- t(apply(regulon.scores, 1, cal_z_score))
#pheatmap(data_subset_norm)

cluster.col <- data.frame(scRNA.scenic@active.ident, row.names = names(scRNA.scenic@active.ident))
colnames(cluster.col) <- "group"


# pheatmap::pheatmap(regulon.scores.scaled, cluster_rows = T,cluster_cols = F, annotation_col = cluster.col, show_colnames = F, fontsize_row=5)
#pheatmap::pheatmap(data_subset_norm, cluster_rows = T,cluster_cols = F, annotation_col = cluster.col, show_colnames = F)


#Average Regulon Activity 平均调控活性
library(AUCell)
regulonAUC <- loadInt(scenicOptions, "aucell_regulonAUC")
regulonAUC <- regulonAUC[onlyNonDuplicatedExtended(rownames(regulonAUC)),]
regulonActivity_byCellType <- sapply(split(rownames(scRNA_sub.nmf@meta.data), scRNA_sub.nmf@meta.data$NMF_gene_celltype),
                                     function(cells) rowMeans(getAUC(regulonAUC)[,cells]))
regulonActivity_byCellType_Scaled <- t(scale(t(regulonActivity_byCellType), center = T, scale=T))
library(ggplot2)
library(cowplot)

png(paste0("plot/",celltype,"/TF_regulonActivity(NMF_gene).png"),units="in", width=8, height=12,res=300)
pheatmap::pheatmap(regulonActivity_byCellType_Scaled,cluster_cols = F,cluster_rows = T,color = colorRampPalette(c(rep("blue",1), "white", rep("red",1)))(100))
dev.off()
}
```
# KEGG分析

```{r}
Idents(scRNA_sub.nmf) <- scRNA_sub.nmf@meta.data$NMF_gene_celltype
df=FindAllMarkers(scRNA_sub.nmf,only.pos = T)


write.csv(df,file =paste0("table/",celltype,"/DEG.CSV"),quote=F)


library(factoextra)
library(FactoMineR)
library(RColorBrewer)
library(R.utils)
library(clusterProfiler)
library(org.Hs.eg.db)
library(KEGG.db)
R.utils::setOption("clusterProfiler.download.method",'auto')


enrich <- list()

for (i in unique(df$cluster)) {
  a <- df %>% 
    filter(cluster == i)
  genelist <- bitr(a$gene,
                   fromType = "SYMBOL",
                   toType = "ENTREZID",
                   OrgDb = "org.Hs.eg.db")
  gene_f <- a %>% 
    right_join(genelist, by = c("gene"="SYMBOL" ))
  enrich[[i]] <- enrichKEGG(gene =  gene_f$ENTREZID,
                            organism     = 'hsa',
                            pvalueCutoff = 0.9,
                            qvalueCutoff =0.9,
                            use_internal_data=T)
  
  # enrich[[i]] <- enrichGO(gene =  gene_f$ENTREZID,
  #                         OrgDb= org.Hs.eg.db,
  #                           pvalueCutoff = 0.1,
  #                           qvalueCutoff = 0.1,
  #                           ont = "BP")
}



## 如果有NULL的无富集结果的情况，需要去除！！！
# 例如
# kegg$NMF_cluster4=NULL
### 有内容的话不去除

celltype_pathway <- data.frame()

for (i in names(enrich)) {
  # i <- names(enrich)[1]
  enrich_single <- enrich[[i]] %>% 
    as.data.frame() %>% 
    rownames_to_column("name")
  enrich_single <- enrich_single %>% 
    mutate(log.p.adjust = -log( enrich_single$p.adjust)) %>% 
    mutate(log.p = -log( enrich_single$pvalue)) %>% 
    mutate(celltype = i)
  celltype_pathway <- rbind(celltype_pathway, enrich_single)    #合并                 
}

celltype_pathway=celltype_pathway[celltype_pathway$pvalue<0.05,]
# celltype_pathway=celltype_pathway[celltype_pathway$p.adjust<0.05,]

kegg_info <- rio::import("table/kegg_info.xlsx")

# rownames(celltype_pathway)=NULL
colnames(celltype_pathway)
celltype_pathway <- celltype_pathway[,c("Description","log.p","celltype")]

## 每个cluster找前3条
# celltype_pathway <- celltype_pathway %>% dplyr::group_by(celltype) %>% slice_head(n = 3)

## 去除kegg疾病pathway
celltype_pathway <- celltype_pathway[!celltype_pathway$Description %in% kegg_info$Pathway[kegg_info$`big annotion` == "Human Diseases"],]

## 每个cluster找前3条
celltype_pathway <- celltype_pathway %>% dplyr::group_by(celltype) %>% slice_head(n = 3)

library(RColorBrewer)
library(ggplot2)
celltype_pathway$Description <- factor(celltype_pathway$Description)


png(paste0("plot/",celltype,"/KEGG(NMF_gene).png"),units="in", width=10, height=10,res=300)
ggplot(celltype_pathway,aes(x=celltype,y=Description))+
  geom_tile(aes(fill=log.p),color = "grey")+
  scale_fill_gradient(low = "#F7ED7A",high = "#E03220")+
  theme_classic()+theme(axis.text.x = element_text(angle=90))+
  labs(title = "KEGG Pathways",
       x = element_blank(),
       y=element_blank()
  )




```

# 免疫检查点
```{r}
cd8_avg=AverageExpression(scRNA_sub.nmf,group.by = 'NMF_gene_celltype')
cd8_avg=as.data.frame(cd8_avg)


coi_gene=read.table('geneset/co-inhibi(NK).txt')
coi_gene=coi_gene$V1


## ss必须把tme放前面！
ss=intersect(coi_gene,rownames(cd8_avg))
rt=cd8_avg[ss,]
rt=rt[rowMeans(rt) != 0,]
png(paste0("plot/",celltype,"/NK_coinhibit(NMF_gene).png"),units="in", width=8, height=12,res=300)
pheatmap::pheatmap(rt,scale = 'row',cluster_cols =F,cluster_rows = F,
                   color = colorRampPalette(c(rep("blue",1), "white", rep("red",1)))(100),border_color = NA,
                  )
dev.off()


cost_gene=read.table('geneset/co-stimu(NK).txt')
cost_gene=cost_gene$V1


## ss必须把tme放前面！
ss=intersect(cost_gene,rownames(cd8_avg))
rt=cd8_avg[ss,]
rt=rt[rowMeans(rt) != 0,]

png(paste0("plot/",celltype,"/NK_costimu(NMF_gene).png"),units="in", width=8, height=12,res=300)
pheatmap::pheatmap(rt,scale = 'row',cluster_cols =F,cluster_rows = F,
                   color = colorRampPalette(c(rep("blue",1), "white", rep("red",1)))(100),border_color = NA,
                  )
dev.off()
```

